pipelines:
  branches:
    master:
      - step:
          deployment: staging
          script:
            - pipe: atlassian/ssh-run:0.4.0
              variables:
                SSH_USER: $USER
                SERVER: $SERVER
                MODE: 'script'
                COMMAND: 'deploy.sh'
                ENV_VARS: >-
                  COMPOSE_FILE='docker-compose-stg.yml'

  custom:
    deploy-master-to-prod:
      - step:
          deployment: production
          script:
            - pipe: atlassian/ssh-run:0.4.0
              variables:
                SSH_USER: $USER
                SERVER: $SERVER
                MODE: 'script'
                COMMAND: 'deploy.sh'
                ENV_VARS: >- 
                  COMPOSE_FILE='docker-compose-prod.yml'
